[[CURRENCIES]]
code="TT"
issuer="GARYZAMOGHGVWLMRUWJBYVC32XVHPXL2R2JAZGDUHCSYWBZLI6ZFG77Z"
name="TradeToken"
desc="TradeToken is a utility token for the TradeToken ecosystem on Pi Testnet."
image="https://tradetoken.github.io/.well-known/tt.png"